name: ml-client-ci

on:
    push:
        branches:
            - main
        paths:
            - "machine-learning-client/**"
    pull_request:
        branches:
            - main
        paths:
            - "machine-learning-client/**"

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              working-directory: ./machine-learning-client
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pipenv
                  pipenv install --dev

            - name: Run tests with coverage
              working-directory: ./machine-learning-client
              run: |
                  pipenv run pytest

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              working-directory: ./machine-learning-client
              run: |
                  docker build -t ml-client:test .

